repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: mixed-line-ending
    -   id: end-of-file-fixer

    -   id: check-ast
    -   id: debug-statements


-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.4.2
    hooks:
    -   id: isort

# flake8
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: flake8
      args:
        - "--max-line-length=88"
        - "--max-complexity=30"
        - "--select=E,B,C,E,F,W,T4,B9"

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: detect-private-key

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: ''  # Use the sha / tag you want to point at
  hooks:
  - id: mypy
    args: [--no-strict-optional,--ignore-missing-imports]
