name: Dev GA test
on:
  push:
    branches:
      - master
      - develop-rewrite
      - develop

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Initialize envrionment
        run: |
          sudo apt update && sudo apt install python3.9 python3.9-venv -y
          python3.9 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
      - run: source venv/bin/activate && python tests/utils.py
      - run: source venv/bin/activate && python tests/exercise.py
      - name: Run safety check
        run: |
          source venv/bin/activate
          which python
          pwd
          ls
          safety check
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
