name: Static code analysis
on:
  push:
    branches:
      - master
      - develop-rewrite
      - develop

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Initialize envrionment
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: python tests/utils.py
      - run: python tests/exercise.py
      - name: Run safety check
        run: |
          safety check
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
