name: Dev GA test
on:
  push:
    branches:
      - master
      - develop-rewrite
      - develop

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: pip install -r requirements.txt
      - run: python tests/exercise.py
      - run: python tests/utils.py
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
